[2023-04-27T07:08:38.680+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag_api.cities.insert_data_Odesa manual__2023-04-27T07:08:06.429483+00:00 [queued]>
[2023-04-27T07:08:38.770+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag_api.cities.insert_data_Odesa manual__2023-04-27T07:08:06.429483+00:00 [queued]>
[2023-04-27T07:08:38.773+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-27T07:08:38.775+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-27T07:08:38.776+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-27T07:08:38.925+0000] {taskinstance.py:1309} INFO - Executing <Task(PostgresOperator): cities.insert_data_Odesa> on 2023-04-27 07:08:06.429483+00:00
[2023-04-27T07:08:38.981+0000] {standard_task_runner.py:55} INFO - Started process 811 to run task
[2023-04-27T07:08:39.025+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'weather_dag_api', 'cities.insert_data_Odesa', 'manual__2023-04-27T07:08:06.429483+00:00', '--job-id', '139', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag_api.py', '--cfg-path', '/tmp/tmpiag58r07']
[2023-04-27T07:08:39.046+0000] {standard_task_runner.py:83} INFO - Job 139: Subtask cities.insert_data_Odesa
[2023-04-27T07:08:39.441+0000] {task_command.py:389} INFO - Running <TaskInstance: weather_dag_api.cities.insert_data_Odesa manual__2023-04-27T07:08:06.429483+00:00 [running]> on host 80d943d8f5b4
[2023-04-27T07:08:40.077+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_dag_api
AIRFLOW_CTX_TASK_ID=cities.insert_data_Odesa
AIRFLOW_CTX_EXECUTION_DATE=2023-04-27T07:08:06.429483+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-27T07:08:06.429483+00:00
[2023-04-27T07:08:40.086+0000] {sql.py:254} INFO - Executing: INSERT INTO measurements (timestamp, temp, precipitation, wind_speed, location) 
				VALUES ('2023-04-26T05:20:00Z',
				12.7,
				0.0,
				6.4,
				'Odesa');
[2023-04-27T07:08:40.211+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-04-27T07:08:41.634+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-04-27T07:08:41.647+0000] {sql.py:375} INFO - Running statement: INSERT INTO measurements (timestamp, temp, precipitation, wind_speed, location) 
				VALUES ('2023-04-26T05:20:00Z',
				12.7,
				0.0,
				6.4,
				'Odesa');, parameters: None
[2023-04-27T07:08:41.651+0000] {sql.py:384} INFO - Rows affected: 1
[2023-04-27T07:08:41.682+0000] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=weather_dag_api, task_id=cities.insert_data_Odesa, execution_date=20230427T070806, start_date=20230427T070838, end_date=20230427T070841
[2023-04-27T07:08:41.761+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-04-27T07:08:41.903+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
