[2023-04-26T18:05:17.297+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag_api.cities.insert_data_Odesa manual__2023-04-26T18:04:38.316670+00:00 [queued]>
[2023-04-26T18:05:17.384+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag_api.cities.insert_data_Odesa manual__2023-04-26T18:04:38.316670+00:00 [queued]>
[2023-04-26T18:05:17.388+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-26T18:05:17.390+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-26T18:05:17.392+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-26T18:05:17.676+0000] {taskinstance.py:1309} INFO - Executing <Task(PostgresOperator): cities.insert_data_Odesa> on 2023-04-26 18:04:38.316670+00:00
[2023-04-26T18:05:17.749+0000] {standard_task_runner.py:55} INFO - Started process 919 to run task
[2023-04-26T18:05:17.797+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'weather_dag_api', 'cities.insert_data_Odesa', 'manual__2023-04-26T18:04:38.316670+00:00', '--job-id', '168', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag_api.py', '--cfg-path', '/tmp/tmp4gfzzshn']
[2023-04-26T18:05:17.842+0000] {standard_task_runner.py:83} INFO - Job 168: Subtask cities.insert_data_Odesa
[2023-04-26T18:05:18.606+0000] {task_command.py:389} INFO - Running <TaskInstance: weather_dag_api.cities.insert_data_Odesa manual__2023-04-26T18:04:38.316670+00:00 [running]> on host b46a99c748bd
[2023-04-26T18:05:19.137+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_dag_api
AIRFLOW_CTX_TASK_ID=cities.insert_data_Odesa
AIRFLOW_CTX_EXECUTION_DATE=2023-04-26T18:04:38.316670+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-26T18:04:38.316670+00:00
[2023-04-26T18:05:19.140+0000] {sql.py:254} INFO - Executing: INSERT INTO measurements (temp) VALUES (15.1);
[2023-04-26T18:05:19.220+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-04-26T18:05:22.809+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-04-26T18:05:22.838+0000] {sql.py:375} INFO - Running statement: INSERT INTO measurements (temp) VALUES (15.1);, parameters: None
[2023-04-26T18:05:22.842+0000] {sql.py:384} INFO - Rows affected: 1
[2023-04-26T18:05:22.925+0000] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=weather_dag_api, task_id=cities.insert_data_Odesa, execution_date=20230426T180438, start_date=20230426T180517, end_date=20230426T180522
[2023-04-26T18:05:23.102+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-04-26T18:05:23.372+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
